/**
 * mcpCatalog.js — Curated "Featured" MCP server registry for the admin
 * MCP Server Marketplace (agent-hub → Integrations → MCP).
 *
 * Extracted out of McpMarketplace.jsx so the catalog can grow without
 * touching the component, and so the live "Browse all" registry tab can
 * sit beside it.
 *
 * Entry shape (only id/name/description/category/transport are required —
 * everything else is optional and degrades gracefully):
 *   {
 *     id, name, description,
 *     icon,                  // emoji fallback (legacy; still rendered when no logo resolves)
 *     category,              // one of CATEGORIES[].id
 *     transport,             // 'stdio' | 'http'
 *     command, args,         // stdio install command
 *     bundled,               // true = first-party server that ships inside the API
 *                            //        image (server/mcpServers/**). `args` then holds
 *                            //        a path relative to the server root, which
 *                            //        core/mcpManager.js resolves before spawning —
 *                            //        nothing is downloaded from npm at install time.
 *     url,                   // http remote URL
 *     configurable_url,      // true = `url` is only a template; the marketplace
 *                            //        prompts the installer for their own endpoint
 *                            //        before saving (self-hosted servers)
 *     required_credentials,  // [{ key, label }]
 *     // ── enrichment for official logos / linking (all optional) ──
 *     logo,                  // explicit logo image URL (wins over derived logos)
 *     repository,            // GitHub repo URL → org avatar is used as the logo
 *     homepage,              // product site → logo.dev domain fallback + "docs" link
 *     verified,              // true = first-party / vendor-published
 *   }
 *
 * Logo resolution (Smithery iconUrl → logo → icon-URL → GitHub avatar →
 * logo.dev → emoji/letter) lives in utils/mcpLogos.jsx.
 */

export const MCP_REGISTRY = [
    // ── Development ──────────────────────────────────────────────────
    { id: 'github', name: 'GitHub', description: 'Repository management, issues, PRs, code search, and CI/CD.', icon: '🐙', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-github'], required_credentials: [{ key: 'GITHUB_PERSONAL_ACCESS_TOKEN', label: 'GitHub PAT' }], repository: 'https://github.com/github/github-mcp-server', verified: true },
    { id: 'gitlab', name: 'GitLab', description: 'Repository management, merge requests, issues, and pipelines.', icon: '🦊', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-gitlab'], required_credentials: [{ key: 'GITLAB_PERSONAL_ACCESS_TOKEN', label: 'GitLab PAT' }, { key: 'GITLAB_API_URL', label: 'GitLab API URL' }], repository: 'https://github.com/gitlabhq/gitlab-mcp' },
    { id: 'bitbucket', name: 'Bitbucket', description: 'Atlassian Bitbucket — repos, pull requests, and code review.', icon: '🪣', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@aashari/mcp-server-atlassian-bitbucket'], required_credentials: [{ key: 'ATLASSIAN_SITE_NAME', label: 'Atlassian Site' }, { key: 'ATLASSIAN_USER_EMAIL', label: 'Atlassian Email' }, { key: 'ATLASSIAN_API_TOKEN', label: 'Atlassian API Token' }], homepage: 'https://bitbucket.org' },
    { id: 'git', name: 'Git', description: 'Read, search, and manipulate local Git repositories.', icon: '📦', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-git'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'filesystem', name: 'Filesystem', description: 'Secure file operations with configurable access controls.', icon: '📁', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '/tmp'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'sentry', name: 'Sentry', description: 'Access error tracking, issues, and performance data.', icon: '🐛', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@sentry/mcp-server'], required_credentials: [{ key: 'SENTRY_AUTH_TOKEN', label: 'Sentry Auth Token' }], repository: 'https://github.com/getsentry/sentry-mcp', verified: true },
    { id: 'playwright', name: 'Playwright', description: 'Browser automation, testing, screenshots, and UI interaction.', icon: '🎭', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@playwright/mcp'], repository: 'https://github.com/microsoft/playwright-mcp', verified: true },
    { id: 'repomix', name: 'Repomix', description: 'Pack entire codebases into AI-friendly formats for analysis.', icon: '📋', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', 'repomix', '--mcp'], repository: 'https://github.com/yamadashy/repomix' },
    { id: 'npm_search', name: 'NPM Search', description: 'Search and discover npm packages with detailed info.', icon: '📦', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', 'npm-search-mcp-server'] },
    { id: 'chrome_devtools', name: 'Chrome DevTools', description: 'Debug, audit performance, and inspect web pages via Chrome.', icon: '🔧', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', 'chrome-devtools-mcp@latest'], repository: 'https://github.com/ChromeDevTools/chrome-devtools-mcp', verified: true },
    { id: 'magic_ui', name: '21st Magic', description: 'Create crafted UI components inspired by top design engineers.', icon: '✨', category: 'development', transport: 'stdio', command: 'npx', args: ['-y', '@21st-dev/magic-mcp'], required_credentials: [{ key: 'TWENTYFIRST_API_KEY', label: '21st.dev API Key' }], repository: 'https://github.com/21st-dev/magic-mcp' },

    // ── Communication ────────────────────────────────────────────────
    { id: 'slack', name: 'Slack', description: 'Send messages, manage channels, and search conversations.', icon: '💬', category: 'communication', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-slack'], required_credentials: [{ key: 'SLACK_BOT_TOKEN', label: 'Slack Bot Token' }, { key: 'SLACK_TEAM_ID', label: 'Slack Team ID' }], repository: 'https://github.com/slackapi/slack-mcp' },
    { id: 'discord', name: 'Discord', description: '50+ tools for Discord server management, messages, and channels.', icon: '🎮', category: 'communication', transport: 'stdio', command: 'npx', args: ['-y', '@scarecr0w12/discord-mcp'], required_credentials: [{ key: 'DISCORD_BOT_TOKEN', label: 'Discord Bot Token' }] },
    { id: 'telegram', name: 'Telegram', description: 'Read/send messages, manage groups, and interact via Telegram.', icon: '✈️', category: 'communication', transport: 'stdio', command: 'npx', args: ['-y', '@chaindead/telegram-mcp'], required_credentials: [{ key: 'TELEGRAM_API_ID', label: 'Telegram API ID' }, { key: 'TELEGRAM_API_HASH', label: 'Telegram API Hash' }] },
    { id: 'email', name: 'Email (IMAP)', description: 'Read, search, send, and manage emails across multiple IMAP/SMTP accounts.', icon: '📧', category: 'communication', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-email'], required_credentials: [{ key: 'IMAP_HOST', label: 'IMAP Host' }, { key: 'EMAIL_USER', label: 'Email Address' }, { key: 'EMAIL_PASS', label: 'Email Password' }] },
    { id: 'soverin', name: 'Soverin', description: 'Soverin mail (soverin.nl) — search, read, send, flag, and move messages in your mailbox.', icon: '📬', category: 'communication', transport: 'stdio', command: 'node', args: ['mcpServers/soverin/index.mjs'], required_credentials: [{ key: 'SOVERIN_EMAIL', label: 'Soverin e-mail address' }, { key: 'SOVERIN_PASSWORD', label: 'Soverin password' }], homepage: 'https://soverin.nl', bundled: true, verified: true },
    { id: 'twilio', name: 'Twilio', description: 'Send SMS, make calls, and manage communication workflows.', icon: '📱', category: 'communication', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-twilio'], required_credentials: [{ key: 'TWILIO_ACCOUNT_SID', label: 'Account SID' }, { key: 'TWILIO_AUTH_TOKEN', label: 'Auth Token' }], homepage: 'https://twilio.com' },

    // ── Productivity & Project Management ─────────────────────────────
    { id: 'google_drive', name: 'Google Drive', description: 'Access, search, and manage Google Drive files and folders.', icon: '📂', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-gdrive'], homepage: 'https://drive.google.com' },
    { id: 'notion', name: 'Notion', description: 'Read, create, and search Notion pages and databases.', icon: '📝', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@notionhq/mcp-server'], required_credentials: [{ key: 'NOTION_API_KEY', label: 'Notion Integration Token' }], repository: 'https://github.com/makenotion/notion-mcp-server', verified: true },
    { id: 'linear', name: 'Linear', description: 'Issue tracking, project management, and team workflows.', icon: '📐', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-linear'], required_credentials: [{ key: 'LINEAR_API_KEY', label: 'Linear API Key' }], homepage: 'https://linear.app' },
    { id: 'jira', name: 'Jira', description: 'Manage issues, search, handle comments, and workflow transitions.', icon: '🔵', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@aashari/mcp-server-atlassian-jira'], required_credentials: [{ key: 'ATLASSIAN_SITE_NAME', label: 'Atlassian Site' }, { key: 'ATLASSIAN_USER_EMAIL', label: 'Atlassian Email' }, { key: 'ATLASSIAN_API_TOKEN', label: 'Atlassian API Token' }], homepage: 'https://atlassian.com' },
    { id: 'confluence', name: 'Confluence', description: 'Search, read, and manage Confluence pages and spaces.', icon: '📘', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@aashari/mcp-server-atlassian-confluence'], required_credentials: [{ key: 'ATLASSIAN_SITE_NAME', label: 'Atlassian Site' }, { key: 'ATLASSIAN_USER_EMAIL', label: 'Atlassian Email' }, { key: 'ATLASSIAN_API_TOKEN', label: 'Atlassian API Token' }], homepage: 'https://atlassian.com' },
    { id: 'trello', name: 'Trello', description: 'Create/move cards, update boards, and track activity.', icon: '📋', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-trello'], required_credentials: [{ key: 'TRELLO_API_KEY', label: 'Trello API Key' }, { key: 'TRELLO_TOKEN', label: 'Trello Token' }], homepage: 'https://trello.com' },
    { id: 'todoist', name: 'Todoist', description: 'Task management, project organization, and productivity tracking.', icon: '✅', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-todoist'], required_credentials: [{ key: 'TODOIST_API_TOKEN', label: 'Todoist API Token' }], homepage: 'https://todoist.com' },
    { id: 'asana', name: 'Asana', description: 'Manage tasks, projects, workspaces, and team assignments.', icon: '🎯', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-asana'], required_credentials: [{ key: 'ASANA_ACCESS_TOKEN', label: 'Asana Access Token' }], homepage: 'https://asana.com' },
    { id: 'google_calendar', name: 'Google Calendar', description: 'View, create, and manage calendar events and schedules.', icon: '📅', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-google-calendar'], homepage: 'https://calendar.google.com' },
    { id: 'google_maps', name: 'Google Maps', description: 'Geocoding, directions, place search, and distance calculations.', icon: '🗺️', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-google-maps'], required_credentials: [{ key: 'GOOGLE_MAPS_API_KEY', label: 'Google Maps API Key' }], homepage: 'https://maps.google.com' },
    { id: 'google_workspace', name: 'Google Workspace', description: '23 tools for Drive, Sheets, Calendar, Docs, and Gmail.', icon: '🏢', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-google-workspace'], homepage: 'https://workspace.google.com' },
    { id: 'airtable', name: 'Airtable', description: 'Access, query, and manage Airtable bases, tables, and records.', icon: '📊', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-airtable'], required_credentials: [{ key: 'AIRTABLE_API_KEY', label: 'Airtable API Key' }], homepage: 'https://airtable.com' },
    { id: 'figma', name: 'Figma', description: 'Access design files, components, styles, and variables.', icon: '🎨', category: 'productivity', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-figma'], required_credentials: [{ key: 'FIGMA_ACCESS_TOKEN', label: 'Figma Access Token' }], homepage: 'https://figma.com' },

    // ── Data & Databases ─────────────────────────────────────────────
    { id: 'postgres', name: 'PostgreSQL', description: 'Query PostgreSQL databases with read-only access.', icon: '🐘', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres'], required_credentials: [{ key: 'POSTGRES_CONNECTION_STRING', label: 'PostgreSQL Connection String' }], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'sqlite', name: 'SQLite', description: 'Read and query local SQLite databases.', icon: '🗄️', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-sqlite'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'redis_mcp', name: 'Redis', description: 'Interact with Redis key-value store, caching, and pub/sub.', icon: '🔴', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-redis'], required_credentials: [{ key: 'REDIS_URL', label: 'Redis URL' }], homepage: 'https://redis.io' },
    { id: 'mysql', name: 'MySQL', description: 'Query MySQL and MariaDB databases with read access.', icon: '🐬', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-mysql'], required_credentials: [{ key: 'MYSQL_HOST', label: 'MySQL Host' }, { key: 'MYSQL_USER', label: 'MySQL User' }, { key: 'MYSQL_PASSWORD', label: 'MySQL Password' }] },
    { id: 'mongodb', name: 'MongoDB', description: 'Query and manage MongoDB collections and documents.', icon: '🍃', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-mongodb'], required_credentials: [{ key: 'MONGODB_URI', label: 'MongoDB Connection URI' }], repository: 'https://github.com/mongodb-js/mongodb-mcp-server', verified: true },
    { id: 'supabase', name: 'Supabase', description: 'SQL queries, database exploration, and Supabase management.', icon: '⚡', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@supabase/mcp-server-supabase'], required_credentials: [{ key: 'SUPABASE_URL', label: 'Supabase URL' }, { key: 'SUPABASE_SERVICE_KEY', label: 'Service Key' }], repository: 'https://github.com/supabase-community/supabase-mcp', verified: true },
    { id: 'clickhouse', name: 'ClickHouse', description: 'Query and inspect ClickHouse analytical databases.', icon: '🔶', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-clickhouse'], required_credentials: [{ key: 'CLICKHOUSE_HOST', label: 'ClickHouse Host' }, { key: 'CLICKHOUSE_PASSWORD', label: 'ClickHouse Password' }], homepage: 'https://clickhouse.com' },
    { id: 'neo4j', name: 'Neo4j', description: 'Query and visualize graph databases with Cypher.', icon: '🕸️', category: 'data', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-neo4j'], required_credentials: [{ key: 'NEO4J_URI', label: 'Neo4j URI' }, { key: 'NEO4J_USER', label: 'Neo4j User' }, { key: 'NEO4J_PASSWORD', label: 'Neo4j Password' }], homepage: 'https://neo4j.com' },

    // ── Search & Web ─────────────────────────────────────────────────
    { id: 'brave_search', name: 'Brave Search', description: 'Web and local search using Brave Search API.', icon: '🦁', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-brave-search'], required_credentials: [{ key: 'BRAVE_API_KEY', label: 'Brave API Key' }], homepage: 'https://brave.com' },
    { id: 'fetch', name: 'Fetch', description: 'Fetch and convert web content for LLM consumption.', icon: '🌐', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-fetch'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'puppeteer', name: 'Puppeteer', description: 'Browser automation, screenshots, and web scraping.', icon: '🕷️', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-puppeteer'] },
    { id: 'exa', name: 'Exa', description: 'Advanced AI-powered web search with up-to-date results.', icon: '🔎', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-exa'], required_credentials: [{ key: 'EXA_API_KEY', label: 'Exa API Key' }], repository: 'https://github.com/exa-labs/exa-mcp-server', verified: true },
    { id: 'context7', name: 'Context7', description: 'Up-to-date code documentation for LLMs and AI editors.', icon: '📚', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@upstash/context7-mcp'], repository: 'https://github.com/upstash/context7', verified: true },
    { id: 'kagi', name: 'Kagi Search', description: 'Premium, ad-free web search via Kagi API.', icon: '🔮', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-kagi'], required_credentials: [{ key: 'KAGI_API_KEY', label: 'Kagi API Key' }], homepage: 'https://kagi.com' },
    { id: 'arxiv', name: 'ArXiv', description: 'Search and read scientific research papers from ArXiv.', icon: '📄', category: 'search', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-arxiv'], homepage: 'https://arxiv.org' },

    // ── AI & Tools ───────────────────────────────────────────────────
    { id: 'memory', name: 'Memory', description: 'Persistent knowledge graph memory for AI conversations.', icon: '🧠', category: 'ai', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'sequential_thinking', name: 'Sequential Thinking', description: 'Dynamic problem-solving through structured thought sequences.', icon: '💭', category: 'ai', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequentialthinking'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },
    { id: 'everart', name: 'EverArt', description: 'AI image generation using multiple models and styles.', icon: '🎨', category: 'ai', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-everart'], required_credentials: [{ key: 'EVERART_API_KEY', label: 'EverArt API Key' }] },
    { id: 'huggingface', name: 'HuggingFace', description: 'Search models, datasets, and Spaces on HuggingFace Hub.', icon: '🤗', category: 'ai', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-huggingface'], required_credentials: [{ key: 'HF_TOKEN', label: 'HuggingFace Token' }], homepage: 'https://huggingface.co' },
    { id: 'langfuse', name: 'Langfuse', description: 'LLM observability — traces, sessions, prompts, and debugging.', icon: '📡', category: 'ai', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-langfuse'], required_credentials: [{ key: 'LANGFUSE_PUBLIC_KEY', label: 'Langfuse Public Key' }, { key: 'LANGFUSE_SECRET_KEY', label: 'Langfuse Secret Key' }], homepage: 'https://langfuse.com' },
    { id: 'everything', name: 'MCP Everything', description: 'Test server demonstrating all MCP protocol features.', icon: '🧪', category: 'ai', transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-everything'], repository: 'https://github.com/modelcontextprotocol/servers', verified: true },

    // ── DevOps & Infrastructure ──────────────────────────────────────
    { id: 'docker', name: 'Docker', description: 'Manage containers, images, networks, and volumes.', icon: '🐳', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', '@thelord/mcp-server-docker-npx'], homepage: 'https://docker.com' },
    { id: 'kubernetes', name: 'Kubernetes', description: 'Manage K8s clusters, pods, deployments, and services.', icon: '☸️', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', 'mcp-server-kubernetes'], homepage: 'https://kubernetes.io' },
    { id: 'aws_kb', name: 'AWS KB Retrieval', description: 'Query AWS Knowledge Bases for RAG-style retrieval.', icon: '☁️', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-aws-kb-retrieval'], required_credentials: [{ key: 'AWS_ACCESS_KEY_ID', label: 'AWS Access Key' }, { key: 'AWS_SECRET_ACCESS_KEY', label: 'AWS Secret Key' }], homepage: 'https://aws.amazon.com' },
    { id: 'cloudflare', name: 'Cloudflare', description: 'Manage Workers, KV, R2, and D1 via Cloudflare API.', icon: '⚡', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-cloudflare'], required_credentials: [{ key: 'CLOUDFLARE_API_TOKEN', label: 'Cloudflare API Token' }], repository: 'https://github.com/cloudflare/mcp-server-cloudflare', verified: true },
    { id: 'vercel', name: 'Vercel', description: 'Manage deployments, domains, and environment variables.', icon: '▲', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-vercel'], required_credentials: [{ key: 'VERCEL_TOKEN', label: 'Vercel Token' }], homepage: 'https://vercel.com' },
    { id: 'github_actions', name: 'GitHub Actions', description: 'Trigger, monitor, and manage CI/CD workflows.', icon: '🔄', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-github-actions'], required_credentials: [{ key: 'GITHUB_PERSONAL_ACCESS_TOKEN', label: 'GitHub PAT' }], homepage: 'https://github.com/features/actions' },
    { id: 'terraform', name: 'Terraform', description: 'Infrastructure as code — plan, apply, and manage resources.', icon: '🏗️', category: 'devops', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-terraform'], repository: 'https://github.com/hashicorp/terraform-mcp-server', verified: true },

    // ── Finance & Commerce ───────────────────────────────────────────
    { id: 'stripe', name: 'Stripe', description: 'Official Stripe integration for payments, subscriptions, and invoices.', icon: '💳', category: 'finance', transport: 'stdio', command: 'npx', args: ['-y', '@stripe/mcp'], required_credentials: [{ key: 'STRIPE_SECRET_KEY', label: 'Stripe Secret Key' }], repository: 'https://github.com/stripe/agent-toolkit', verified: true },
    { id: 'shopify', name: 'Shopify', description: 'Manage products, orders, customers, and store data.', icon: '🛒', category: 'finance', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-shopify'], required_credentials: [{ key: 'SHOPIFY_ACCESS_TOKEN', label: 'Shopify Access Token' }, { key: 'SHOPIFY_STORE_URL', label: 'Store URL' }], homepage: 'https://shopify.com' },
    { id: 'coinmarket', name: 'CoinMarketCap', description: 'Cryptocurrency listings, prices, and market data.', icon: '₿', category: 'finance', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-coinmarket'], required_credentials: [{ key: 'COINMARKETCAP_API_KEY', label: 'CoinMarketCap API Key' }], homepage: 'https://coinmarketcap.com' },

    // ── Analytics & Monitoring ───────────────────────────────────────
    { id: 'posthog', name: 'PostHog', description: 'Product analytics, user tracking, and A/B testing data.', icon: '🦔', category: 'analytics', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-posthog'], required_credentials: [{ key: 'POSTHOG_API_KEY', label: 'PostHog API Key' }, { key: 'POSTHOG_HOST', label: 'PostHog Host' }], repository: 'https://github.com/PostHog/mcp', verified: true },
    { id: 'grafana', name: 'Grafana', description: 'Search dashboards, investigate incidents, and query data sources.', icon: '📊', category: 'analytics', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-grafana'], required_credentials: [{ key: 'GRAFANA_URL', label: 'Grafana URL' }, { key: 'GRAFANA_API_KEY', label: 'Grafana API Key' }], repository: 'https://github.com/grafana/mcp-grafana', verified: true },
    { id: 'datadog', name: 'Datadog', description: 'Monitor infrastructure, APM, logs, and metrics.', icon: '🐕', category: 'analytics', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-datadog'], required_credentials: [{ key: 'DD_API_KEY', label: 'Datadog API Key' }, { key: 'DD_APP_KEY', label: 'Datadog App Key' }], homepage: 'https://datadoghq.com' },
    { id: 'openobserve', name: 'OpenObserve', description: 'Query logs, metrics, and traces; manage dashboards, alerts, and pipelines.', icon: '🔭', category: 'analytics', transport: 'http', url: 'https://<your-openobserve-host>/api/<org>/mcp', configurable_url: true, required_credentials: [{ key: 'AUTHORIZATION', label: 'Authorization header (Basic <base64 of email:password>)' }], repository: 'https://github.com/openobserve/openobserve', homepage: 'https://openobserve.ai', verified: true },

    // ── SEO & Marketing ──────────────────────────────────────────────
    { id: 'google_search_console', name: 'Google Search Console', description: 'Search analytics, indexing status, sitemaps, and query/page performance.', icon: '🔍', category: 'seo', transport: 'stdio', command: 'npx', args: ['-y', 'mcp-server-gsc'], required_credentials: [{ key: 'GOOGLE_APPLICATION_CREDENTIALS', label: 'Service Account JSON path' }], repository: 'https://github.com/ahonn/mcp-server-gsc', homepage: 'https://search.google.com/search-console' },
    { id: 'dataforseo', name: 'DataForSEO', description: 'SERP, keyword, backlink, on-page and rank-tracking data via DataForSEO.', icon: '📈', category: 'seo', transport: 'stdio', command: 'npx', args: ['-y', 'dataforseo-mcp-server'], required_credentials: [{ key: 'DATAFORSEO_USERNAME', label: 'DataForSEO Username' }, { key: 'DATAFORSEO_PASSWORD', label: 'DataForSEO Password' }], repository: 'https://github.com/dataforseo/mcp-server-typescript', homepage: 'https://dataforseo.com', verified: true },
    { id: 'google_analytics', name: 'Google Analytics', description: 'GA4 reporting — traffic, conversions, audiences, and realtime data.', icon: '📊', category: 'seo', transport: 'stdio', command: 'npx', args: ['-y', 'mcp-server-google-analytics'], required_credentials: [{ key: 'GA_PROPERTY_ID', label: 'GA4 Property ID' }, { key: 'GOOGLE_APPLICATION_CREDENTIALS', label: 'Service Account JSON path' }], homepage: 'https://analytics.google.com' },
    { id: 'google_ads', name: 'Google Ads', description: 'Campaigns, ad groups, keywords, and performance reporting for Google Ads.', icon: '📣', category: 'seo', transport: 'stdio', command: 'npx', args: ['-y', 'google-ads-mcp'], required_credentials: [{ key: 'GOOGLE_ADS_DEVELOPER_TOKEN', label: 'Developer Token' }, { key: 'GOOGLE_ADS_CLIENT_ID', label: 'OAuth Client ID' }, { key: 'GOOGLE_ADS_CLIENT_SECRET', label: 'OAuth Client Secret' }, { key: 'GOOGLE_ADS_REFRESH_TOKEN', label: 'Refresh Token' }], homepage: 'https://ads.google.com' },
    { id: 'ahrefs', name: 'Ahrefs', description: 'Backlinks, organic keywords, site audit, and rank tracking via Ahrefs.', icon: '🧭', category: 'seo', transport: 'http', url: 'https://api.ahrefs.com/mcp', required_credentials: [{ key: 'API_KEY', label: 'Ahrefs API Key' }], homepage: 'https://ahrefs.com', verified: true },
    { id: 'semrush', name: 'Semrush', description: 'Domain analytics, keyword research, position tracking, and competitor data.', icon: '🟠', category: 'seo', transport: 'stdio', command: 'npx', args: ['-y', 'semrush-mcp'], required_credentials: [{ key: 'SEMRUSH_API_KEY', label: 'Semrush API Key' }], homepage: 'https://semrush.com' },

    // ── Social Media ─────────────────────────────────────────────────
    { id: 'twitter', name: 'Twitter / X', description: 'Post tweets, search, read timelines, and manage engagement.', icon: '🐦', category: 'social', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-twitter'], required_credentials: [{ key: 'TWITTER_API_KEY', label: 'Twitter API Key' }, { key: 'TWITTER_API_SECRET', label: 'Twitter API Secret' }], homepage: 'https://x.com' },
    { id: 'bluesky', name: 'Bluesky', description: 'Post, search, and interact on the Bluesky social network.', icon: '🦋', category: 'social', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-bluesky'], required_credentials: [{ key: 'BLUESKY_HANDLE', label: 'Bluesky Handle' }, { key: 'BLUESKY_APP_PASSWORD', label: 'App Password' }], homepage: 'https://bsky.app' },
    { id: 'youtube', name: 'YouTube', description: 'Search videos, fetch transcripts, and analyze channels.', icon: '▶️', category: 'social', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-youtube'], required_credentials: [{ key: 'YOUTUBE_API_KEY', label: 'YouTube API Key' }], homepage: 'https://youtube.com' },
    { id: 'reddit', name: 'Reddit', description: 'Browse posts, search content, and analyze subreddit activity.', icon: '🤖', category: 'social', transport: 'stdio', command: 'npx', args: ['-y', '@anthropic/mcp-server-reddit'], homepage: 'https://reddit.com' },

    // ── Smart home / IoT ─────────────────────────────────────────────
    // Bundled: Tuya publishes no MCP server for device control, and the
    // third-party ones would be handed the user's Access Secret.
    { id: 'tuya', name: 'Tuya', description: 'Tuya / Smart Life smart home — list devices, read status, switch lights and plugs, and run scenes.', icon: '🏠', category: 'iot', transport: 'stdio', command: 'node', args: ['mcpServers/tuya/index.mjs'], required_credentials: [{ key: 'TUYA_ACCESS_ID', label: 'Tuya Access ID' }, { key: 'TUYA_ACCESS_SECRET', label: 'Tuya Access Secret' }, { key: 'TUYA_UID', label: 'Smart Life app account UID' }, { key: 'TUYA_REGION', label: 'Data center (eu / weu / us / cn / in)' }], homepage: 'https://developer.tuya.com', bundled: true, verified: true },
];

export const CATEGORIES = [
    { id: 'all', label: 'All', icon: '🔮' },
    { id: 'development', label: 'Development', icon: '💻' },
    { id: 'communication', label: 'Communication', icon: '💬' },
    { id: 'productivity', label: 'Productivity', icon: '📋' },
    { id: 'data', label: 'Data', icon: '🗄️' },
    { id: 'search', label: 'Search & Web', icon: '🔍' },
    { id: 'ai', label: 'AI & Tools', icon: '🤖' },
    { id: 'devops', label: 'DevOps', icon: '🚀' },
    { id: 'finance', label: 'Finance', icon: '💳' },
    { id: 'analytics', label: 'Analytics', icon: '📊' },
    { id: 'seo', label: 'SEO & Marketing', icon: '📈' },
    { id: 'social', label: 'Social', icon: '🌐' },
    { id: 'iot', label: 'Smart home', icon: '🏠' },
];
