import React, { useCallback, useEffect, useState } from 'react';
import { Check, Eye, EyeOff, Loader2, RefreshCw, Trash2 } from 'lucide-react';
import { API_BASE, authFetch } from '../../../utils/helpers';

/**
 * Release notes review queue — the human gate.
 *
 * The build pipeline drafts notes on every dev and prod build and files them as
 * `draft`. Nothing here is public until someone presses Publish, which is the
 * entire point: the copy is machine-written and a customer should never be the
 * first human to read it.
 *
 * The rolling "Unreleased" entry (no version) is regenerated by each dev build,
 * so edits to it are provisional — the store refuses to overwrite it once it has
 * been published, but an unpublished edit will be replaced by the next build.
 * The panel says so rather than letting someone lose work silently.
 */

const KIND_LABELS = { feature: 'New', improvement: 'Improved', fix: 'Fixed' };
const KIND_ORDER = ['feature', 'improvement', 'fix'];

export default function ReleaseNotesPanel() {
    const [entries, setEntries] = useState([]);
    const [loading, setLoading] = useState(true);
    const [busyId, setBusyId] = useState(null);
    const [error, setError] = useState('');

    const load = useCallback(async () => {
        setLoading(true);
        setError('');
        try {
            const res = await authFetch(`${API_BASE}/api/release-notes/admin`);
            if (!res.ok) throw new Error(`Request failed (${res.status})`);
            const data = await res.json();
            setEntries(Array.isArray(data.entries) ? data.entries : []);
        } catch (e) {
            setError(e.message || 'Could not load release notes');
        }
        setLoading(false);
    }, []);

    useEffect(() => { load(); }, [load]);

    const act = async (id, path, method = 'POST', body) => {
        setBusyId(id);
        setError('');
        try {
            const res = await authFetch(`${API_BASE}/api/release-notes/admin/${id}${path}`, {
                method,
                ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}),
            });
            if (!res.ok) throw new Error(`Request failed (${res.status})`);
            await load();
        } catch (e) {
            setError(e.message || 'Action failed');
        }
        setBusyId(null);
    };

    const patch = (id, fields) => act(id, '', 'PUT', fields);

    if (loading) {
        return (
            <div className="flex items-center justify-center h-full gap-2" style={{ color: 'var(--text-secondary)' }}>
                <Loader2 className="w-4 h-4 animate-spin" /> Loading release notes…
            </div>
        );
    }

    return (
        <div className="h-full overflow-y-auto p-6" style={{ background: 'var(--bg-primary)' }}>
            <div className="flex items-center justify-between mb-4">
                <div>
                    <h1 className="text-lg font-semibold" style={{ color: 'var(--text-primary)' }}>Release notes</h1>
                    <p className="text-xs mt-0.5" style={{ color: 'var(--text-secondary)' }}>
                        Drafted automatically on every build. Nothing appears on the website until you publish it.
                    </p>
                </div>
                <button
                    onClick={load}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium border"
                    style={{ borderColor: 'var(--border-default)', color: 'var(--text-secondary)' }}
                >
                    <RefreshCw className="w-3.5 h-3.5" /> Refresh
                </button>
            </div>

            {error ? (
                <div className="mb-4 px-3 py-2 rounded-md text-xs"
                     style={{ background: 'rgba(239,68,68,0.1)', color: 'rgb(185,28,28)' }}>
                    {error}
                </div>
            ) : null}

            {entries.length === 0 ? (
                <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                    No release notes yet. They appear here after the next build.
                </p>
            ) : null}

            <div className="flex flex-col gap-4">
                {entries.map(entry => {
                    const published = entry.status === 'published';
                    const rolling = !entry.version;
                    const busy = busyId === entry.id;
                    return (
                        <div key={entry.id} className="rounded-lg border p-4"
                             style={{ borderColor: 'var(--border-default)', background: 'var(--bg-card)' }}>
                            <div className="flex items-start justify-between gap-3 mb-2">
                                <div className="flex items-center gap-2 flex-wrap">
                                    <span className="px-2 py-0.5 rounded text-[11px] font-semibold"
                                          style={{ background: 'var(--bg-tertiary)', color: 'var(--text-primary)' }}>
                                        {entry.version || 'Unreleased'}
                                    </span>
                                    <span className="px-2 py-0.5 rounded text-[11px] font-medium"
                                          style={published
                                              ? { background: 'rgba(34,197,94,0.12)', color: 'rgb(21,128,61)' }
                                              : { background: 'rgba(245,158,11,0.12)', color: 'rgb(146,64,14)' }}>
                                        {published ? 'Published' : 'Draft'}
                                    </span>
                                    {entry.services ? (
                                        <span className="text-[11px]" style={{ color: 'var(--text-muted)' }}>
                                            {entry.services}
                                        </span>
                                    ) : null}
                                </div>
                                <div className="flex items-center gap-1.5 shrink-0">
                                    {published ? (
                                        <button
                                            disabled={busy}
                                            onClick={() => act(entry.id, '/unpublish')}
                                            className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-xs border"
                                            style={{ borderColor: 'var(--border-default)', color: 'var(--text-secondary)' }}
                                        >
                                            <EyeOff className="w-3.5 h-3.5" /> Unpublish
                                        </button>
                                    ) : (
                                        <button
                                            disabled={busy}
                                            onClick={() => act(entry.id, '/publish')}
                                            className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-medium"
                                            style={{ background: 'var(--accent-primary)', color: '#fff' }}
                                        >
                                            <Check className="w-3.5 h-3.5" /> Publish
                                        </button>
                                    )}
                                    <button
                                        disabled={busy}
                                        onClick={() => act(entry.id, '', 'DELETE')}
                                        className="p-1.5 rounded-md"
                                        style={{ color: 'var(--text-muted)' }}
                                        title="Discard"
                                    >
                                        <Trash2 className="w-3.5 h-3.5" />
                                    </button>
                                </div>
                            </div>

                            {rolling && !published ? (
                                <p className="text-[11px] mb-2" style={{ color: 'var(--text-muted)' }}>
                                    This is the rolling draft — the next build will regenerate it, replacing any edits.
                                    Publish it to freeze the copy.
                                </p>
                            ) : null}

                            <input
                                className="w-full mb-2 px-2 py-1.5 rounded-md text-sm border bg-transparent"
                                style={{ borderColor: 'var(--border-default)', color: 'var(--text-primary)' }}
                                value={entry.title || ''}
                                placeholder="Headline"
                                onChange={e => setEntries(prev => prev.map(x => x.id === entry.id ? { ...x, title: e.target.value } : x))}
                                onBlur={e => patch(entry.id, { title: e.target.value })}
                            />
                            <textarea
                                className="w-full mb-3 px-2 py-1.5 rounded-md text-sm border bg-transparent"
                                style={{ borderColor: 'var(--border-default)', color: 'var(--text-secondary)' }}
                                rows={2}
                                value={entry.lead || ''}
                                placeholder="One or two sentences for a customer"
                                onChange={e => setEntries(prev => prev.map(x => x.id === entry.id ? { ...x, lead: e.target.value } : x))}
                                onBlur={e => patch(entry.id, { lead: e.target.value })}
                            />

                            {KIND_ORDER.map(kind => {
                                const items = (entry.items || []).filter(i => i && i.kind === kind);
                                if (!items.length) return null;
                                return (
                                    <div key={kind} className="mb-2">
                                        <div className="text-[11px] font-semibold uppercase tracking-wide mb-1"
                                             style={{ color: 'var(--text-secondary)' }}>
                                            {KIND_LABELS[kind]}
                                        </div>
                                        <ul className="text-xs pl-4 list-disc flex flex-col gap-1"
                                            style={{ color: 'var(--text-secondary)' }}>
                                            {items.map((it, i) => (
                                                <li key={i}>
                                                    <strong style={{ color: 'var(--text-primary)' }}>{it.title}</strong>
                                                    {it.title && it.body ? ' — ' : null}{it.body}
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                );
                            })}

                            {published && entry.publishedAt ? (
                                <div className="mt-2 flex items-center gap-1 text-[11px]" style={{ color: 'var(--text-muted)' }}>
                                    <Eye className="w-3 h-3" /> Live since {new Date(entry.publishedAt).toLocaleDateString()}
                                </div>
                            ) : null}
                        </div>
                    );
                })}
            </div>
        </div>
    );
}
