export const ALL_PROMPTS = [
    { text: "Explain quantum computing like I'm five", icon: "⚛️" },
    { text: "Draft a professional email to my boss about a raise", icon: "📧" },
    { text: "Write a short story about a detective who is a cat", icon: "🐱" },
    { text: "Give me a 7-day healthy meal plan for a vegetarian", icon: "🥗" },
    { text: "Summarize the main themes of the movie Interstellar", icon: "🎬" },
    { text: "Write a Python function to check for prime numbers", icon: "🐍" },
    { text: "Brainstorm 10 names for a new pet grooming business", icon: "💡" },
    { text: "How do I make a perfect chocolate chip cookie?", icon: "🍪" },
    { text: "Write a funny poem about Mondays", icon: "✍️" },
    { text: "Explain the difference between a mortgage and a loan", icon: "💰" },
    { text: "Create a 3-day travel itinerary for Tokyo", icon: "✈️" },
    { text: "Write a React component for a reusable modal", icon: "⚛️" },
    { text: "What are the key benefits of meditation?", icon: "🧘" },
    { text: "Help me write a LinkedIn post about my new job", icon: "💼" },
    { text: "Translate 'Where is the nearest library?' into French", icon: "🇫🇷" },
    { text: "Explain how a blockchain works in simple terms", icon: "⛓️" },
    { text: "Give me a list of low-impact exercises for seniors", icon: "🏃" },
    { text: "Write a SQL query to find the top 5 customers by sales", icon: "📊" },
    { text: "Brainstorm plot twists for a sci-fi novel", icon: "🚀" },
    { text: "How do I remove a red wine stain from a carpet?", icon: "🧼" },
    { text: "Write a formal apology letter for a missed meeting", icon: "📝" },
    { text: "Explain the theory of relativity to a teenager", icon: "🌗" },
    { text: "What are some high-protein snacks for gym goers?", icon: "🍗" },
    { text: "Create a workout routine focusing on core strength", icon: "💪" },
    { text: "Write a blog post intro about sustainable fashion", icon: "👗" },
    { text: "How does the stock market work for beginners?", icon: "📈" },
    { text: "Give me 5 gift ideas for a 30th birthday", icon: "🎁" },
    { text: "Write a script for a 30-second commercial for coffee", icon: "☕" },
    { text: "Explain why the sky is blue", icon: "🌤️" },
    { text: "What are the most common coding interview questions?", icon: "💻" },
    { text: "Draft a polite decline for a wedding invitation", icon: "💌" },
    { text: "Write a regex to validate an email address", icon: "🔍" },
    { text: "How can I improve my sleep quality?", icon: "😴" },
    { text: "Create a list of must-read books for entrepreneurs", icon: "📚" },
    { text: "Explain the concept of 'opportunity cost'", icon: "📉" },
    { text: "Write a CSS snippet for a glassmorphism effect", icon: "🎨" },
    { text: "What are the best practices for remote work?", icon: "🏠" },
    { text: "How do I start a podcast on a budget?", icon: "🎙️" },
    { text: "Write a motivational speech for a graduation", icon: "🎓" },
    { text: "Explain the greenhouse effect", icon: "🌿" },
    { text: "Give me 10 trivia questions about world geography", icon: "🌍" },
    { text: "Write a pitch for a mobile app idea", icon: "📱" },
    { text: "How to stay productive while working from home?", icon: "⏱️" },
    { text: "What are the benefits of learning a second language?", icon: "🗣️" },
    { text: "Write a recipe for a classic pesto sauce", icon: "🌿" },
    { text: "Explain the basics of photography composition", icon: "📷" },
    { text: "Give me ideas for a themed dinner party", icon: "🍽️" },
    { text: "Write a cover letter for a software engineer position", icon: "👨‍💻" },
    { text: "How do I effectively manage my time?", icon: "📅" },
    { text: "What are the essential items for a hiking trip?", icon: "🥾" },
    { text: "Write a review of a fictional futuristic gadget", icon: "📡" },
    { text: "Explain how the internet works in 3 paragraphs", icon: "🌐" },
    { text: "Give me a list of self-care activities for a rainy day", icon: "🕯️" },
    { text: "Write a bash script to backup a directory", icon: "🐚" },
    { text: "How to prepare for a public speaking engagement?", icon: "🎤" },
    { text: "What are the pros and cons of electric cars?", icon: "⚡" },
    { text: "Write a thank you note for a baby shower gift", icon: "👶" },
    { text: "Explain the importance of biodiversity", icon: "🦋" },
    { text: "Give me tips for learning to play the guitar", icon: "🎸" },
    { text: "Write a social media caption for a sunset photo", icon: "🌇" },
    { text: "How do I bake a loaf of sourdough bread?", icon: "🍞" },
    { text: "What are the main differences between Mac and Windows?", icon: "💻" },
    { text: "Write an outline for a 10-minute presentation", icon: "📊" },
    { text: "Explain the concept of 'growth mindset'", icon: "🌱" },
    { text: "Give me 5 interesting facts about space", icon: "☄️" },
    { text: "Write a cold email to a potential mentor", icon: "🤝" },
    { text: "How can I save money on my monthly groceries?", icon: "🛒" },
    { text: "What are the best indoor plants for low light?", icon: "🪴" },
    { text: "Write a dialogue between a robot and a philosopher", icon: "🤖" },
    { text: "Explain how a microwave heats food", icon: "♨️" },
    { text: "Give me a list of productive habits to start", icon: "✅" },
    { text: "Write a press release for a new product launch", icon: "🗞️" },
    { text: "How to fix a leaky faucet in 5 steps?", icon: "🔧" },
    { text: "What are the components of a healthy relationship?", icon: "❤️" },
    { text: "Write a song lyric about finding your path", icon: "🎵" },
    { text: "Explain why leaves change color in the fall", icon: "🍂" },
    { text: "Give me tips for organizing a small apartment", icon: "📦" },
    { text: "Write a letter to your future self in 5 years", icon: "✉️" },
    { text: "How to prepare a garden for the spring?", icon: "🌻" },
    { text: "What are some common myths about nutrition?", icon: "🍎" },
    { text: "Write a short bio for a professional website", icon: "👤" },
    { text: "Explain the water cycle to a 2nd grader", icon: "💧" },
    { text: "Give me ideas for a low-cost date night", icon: "🌙" },
    { text: "Write a guide on how to stay safe online", icon: "🛡️" },
    { text: "How do I choose the right laptop for college?", icon: "🎓" },
    { text: "What are the benefits of drinking green tea?", icon: "🍵" },
    { text: "Write a job description for a social media manager", icon: "📱" },
    { text: "Explain how an airplane stays in the air", icon: "✈️" },
    { text: "Give me a list of fun hobbies to try this year", icon: "🎨" },
    { text: "Write an invitation for a housewarming party", icon: "🏠" },
    { text: "How to build a basic personal budget in Excel?", icon: "📉" },
    { text: "What are the best ways to learn a new skill fast?", icon: "⚡" },
    { text: "Write a script for a travel vlog about Rome", icon: "🇮🇹" },
    { text: "Explain the basics of cryptocurrency mining", icon: "⛏️" },
    { text: "Give me 5 recipes using only 5 ingredients", icon: "🍳" },
    { text: "Write a motivational quote for someone struggling", icon: "🌟" },
    { text: "How do I improve my typing speed?", icon: "⌨️" },
    { text: "What are the advantages of urban gardening?", icon: "🏙️" },
    { text: "Write a paragraph about the history of jazz", icon: "🎷" },
    { text: "Explain the difference between AI and ML", icon: "🤖" },
    { text: "Give me tips for taking better photos on a phone", icon: "🤳" }
];

export const WELCOME_MESSAGES = [
    "Where should we start?",
    "How can I help you today?",
    "What's on your mind?",
    "Let's build something great.",
    "Ready to explore?",
    "What are we working on?",
    "Ask me anything.",
    "Let's get started.",
    "How can I assist you?",
    "Need a hand with something?"
];
