export const ALL_PROMPTS = [
    { text: "Explain quantum computing like I'm five", icon: "⚛️", i18nKey: "starter.prompt_0" },
    { text: "Draft a professional email to my boss about a raise", icon: "📧", i18nKey: "starter.prompt_1" },
    { text: "Write a short story about a detective who is a cat", icon: "🐱", i18nKey: "starter.prompt_2" },
    { text: "Give me a 7-day healthy meal plan for a vegetarian", icon: "🥗", i18nKey: "starter.prompt_3" },
    { text: "Summarize the main themes of the movie Interstellar", icon: "🎬", i18nKey: "starter.prompt_4" },
    { text: "Write a Python function to check for prime numbers", icon: "🐍", i18nKey: "starter.prompt_5" },
    { text: "Brainstorm 10 names for a new pet grooming business", icon: "💡", i18nKey: "starter.prompt_6" },
    { text: "How do I make a perfect chocolate chip cookie?", icon: "🍪", i18nKey: "starter.prompt_7" },
    { text: "Write a funny poem about Mondays", icon: "✍️", i18nKey: "starter.prompt_8" },
    { text: "Explain the difference between a mortgage and a loan", icon: "💰", i18nKey: "starter.prompt_9" },
    { text: "Create a 3-day travel itinerary for Tokyo", icon: "✈️", i18nKey: "starter.prompt_10" },
    { text: "Write a React component for a reusable modal", icon: "⚛️", i18nKey: "starter.prompt_11" },
    { text: "What are the key benefits of meditation?", icon: "🧘", i18nKey: "starter.prompt_12" },
    { text: "Help me write a LinkedIn post about my new job", icon: "💼", i18nKey: "starter.prompt_13" },
    { text: "Translate 'Where is the nearest library?' into French", icon: "🇫🇷", i18nKey: "starter.prompt_14" },
    { text: "Explain how a blockchain works in simple terms", icon: "⛓️", i18nKey: "starter.prompt_15" },
    { text: "Give me a list of low-impact exercises for seniors", icon: "🏃", i18nKey: "starter.prompt_16" },
    { text: "Write a SQL query to find the top 5 customers by sales", icon: "📊", i18nKey: "starter.prompt_17" },
    { text: "Brainstorm plot twists for a sci-fi novel", icon: "🚀", i18nKey: "starter.prompt_18" },
    { text: "How do I remove a red wine stain from a carpet?", icon: "🧼", i18nKey: "starter.prompt_19" },
    { text: "Write a formal apology letter for a missed meeting", icon: "📝", i18nKey: "starter.prompt_20" },
    { text: "Explain the theory of relativity to a teenager", icon: "🌗", i18nKey: "starter.prompt_21" },
    { text: "What are some high-protein snacks for gym goers?", icon: "🍗", i18nKey: "starter.prompt_22" },
    { text: "Create a workout routine focusing on core strength", icon: "💪", i18nKey: "starter.prompt_23" },
    { text: "Write a blog post intro about sustainable fashion", icon: "👗", i18nKey: "starter.prompt_24" },
    { text: "How does the stock market work for beginners?", icon: "📈", i18nKey: "starter.prompt_25" },
    { text: "Give me 5 gift ideas for a 30th birthday", icon: "🎁", i18nKey: "starter.prompt_26" },
    { text: "Write a script for a 30-second commercial for coffee", icon: "☕", i18nKey: "starter.prompt_27" },
    { text: "Explain why the sky is blue", icon: "🌤️", i18nKey: "starter.prompt_28" },
    { text: "What are the most common coding interview questions?", icon: "💻", i18nKey: "starter.prompt_29" },
    { text: "Draft a polite decline for a wedding invitation", icon: "💌", i18nKey: "starter.prompt_30" },
    { text: "Write a regex to validate an email address", icon: "🔍", i18nKey: "starter.prompt_31" },
    { text: "How can I improve my sleep quality?", icon: "😴", i18nKey: "starter.prompt_32" },
    { text: "Create a list of must-read books for entrepreneurs", icon: "📚", i18nKey: "starter.prompt_33" },
    { text: "Explain the concept of 'opportunity cost'", icon: "📉", i18nKey: "starter.prompt_34" },
    { text: "Write a CSS snippet for a glassmorphism effect", icon: "🎨", i18nKey: "starter.prompt_35" },
    { text: "What are the best practices for remote work?", icon: "🏠", i18nKey: "starter.prompt_36" },
    { text: "How do I start a podcast on a budget?", icon: "🎙️", i18nKey: "starter.prompt_37" },
    { text: "Write a motivational speech for a graduation", icon: "🎓", i18nKey: "starter.prompt_38" },
    { text: "Explain the greenhouse effect", icon: "🌿", i18nKey: "starter.prompt_39" },
    { text: "Give me 10 trivia questions about world geography", icon: "🌍", i18nKey: "starter.prompt_40" },
    { text: "Write a pitch for a mobile app idea", icon: "📱", i18nKey: "starter.prompt_41" },
    { text: "How to stay productive while working from home?", icon: "⏱️", i18nKey: "starter.prompt_42" },
    { text: "What are the benefits of learning a second language?", icon: "🗣️", i18nKey: "starter.prompt_43" },
    { text: "Write a recipe for a classic pesto sauce", icon: "🌿", i18nKey: "starter.prompt_44" },
    { text: "Explain the basics of photography composition", icon: "📷", i18nKey: "starter.prompt_45" },
    { text: "Give me ideas for a themed dinner party", icon: "🍽️", i18nKey: "starter.prompt_46" },
    { text: "Write a cover letter for a software engineer position", icon: "👨‍💻", i18nKey: "starter.prompt_47" },
    { text: "How do I effectively manage my time?", icon: "📅", i18nKey: "starter.prompt_48" },
    { text: "What are the essential items for a hiking trip?", icon: "🥾", i18nKey: "starter.prompt_49" },
    { text: "Write a review of a fictional futuristic gadget", icon: "📡", i18nKey: "starter.prompt_50" },
    { text: "Explain how the internet works in 3 paragraphs", icon: "🌐", i18nKey: "starter.prompt_51" },
    { text: "Give me a list of self-care activities for a rainy day", icon: "🕯️", i18nKey: "starter.prompt_52" },
    { text: "Write a bash script to backup a directory", icon: "🐚", i18nKey: "starter.prompt_53" },
    { text: "How to prepare for a public speaking engagement?", icon: "🎤", i18nKey: "starter.prompt_54" },
    { text: "What are the pros and cons of electric cars?", icon: "⚡", i18nKey: "starter.prompt_55" },
    { text: "Write a thank you note for a baby shower gift", icon: "👶", i18nKey: "starter.prompt_56" },
    { text: "Explain the importance of biodiversity", icon: "🦋", i18nKey: "starter.prompt_57" },
    { text: "Give me tips for learning to play the guitar", icon: "🎸", i18nKey: "starter.prompt_58" },
    { text: "Write a social media caption for a sunset photo", icon: "🌇", i18nKey: "starter.prompt_59" },
    { text: "How do I bake a loaf of sourdough bread?", icon: "🍞", i18nKey: "starter.prompt_60" },
    { text: "What are the main differences between Mac and Windows?", icon: "💻", i18nKey: "starter.prompt_61" },
    { text: "Write an outline for a 10-minute presentation", icon: "📊", i18nKey: "starter.prompt_62" },
    { text: "Explain the concept of 'growth mindset'", icon: "🌱", i18nKey: "starter.prompt_63" },
    { text: "Give me 5 interesting facts about space", icon: "☄️", i18nKey: "starter.prompt_64" },
    { text: "Write a cold email to a potential mentor", icon: "🤝", i18nKey: "starter.prompt_65" },
    { text: "How can I save money on my monthly groceries?", icon: "🛒", i18nKey: "starter.prompt_66" },
    { text: "What are the best indoor plants for low light?", icon: "🪴", i18nKey: "starter.prompt_67" },
    { text: "Write a dialogue between a robot and a philosopher", icon: "🤖", i18nKey: "starter.prompt_68" },
    { text: "Explain how a microwave heats food", icon: "♨️", i18nKey: "starter.prompt_69" },
    { text: "Give me a list of productive habits to start", icon: "✅", i18nKey: "starter.prompt_70" },
    { text: "Write a press release for a new product launch", icon: "🗞️", i18nKey: "starter.prompt_71" },
    { text: "How to fix a leaky faucet in 5 steps?", icon: "🔧", i18nKey: "starter.prompt_72" },
    { text: "What are the components of a healthy relationship?", icon: "❤️", i18nKey: "starter.prompt_73" },
    { text: "Write a song lyric about finding your path", icon: "🎵", i18nKey: "starter.prompt_74" },
    { text: "Explain why leaves change color in the fall", icon: "🍂", i18nKey: "starter.prompt_75" },
    { text: "Give me tips for organizing a small apartment", icon: "📦", i18nKey: "starter.prompt_76" },
    { text: "Write a letter to your future self in 5 years", icon: "✉️", i18nKey: "starter.prompt_77" },
    { text: "How to prepare a garden for the spring?", icon: "🌻", i18nKey: "starter.prompt_78" },
    { text: "What are some common myths about nutrition?", icon: "🍎", i18nKey: "starter.prompt_79" },
    { text: "Write a short bio for a professional website", icon: "👤", i18nKey: "starter.prompt_80" },
    { text: "Explain the water cycle to a 2nd grader", icon: "💧", i18nKey: "starter.prompt_81" },
    { text: "Give me ideas for a low-cost date night", icon: "🌙", i18nKey: "starter.prompt_82" },
    { text: "Write a guide on how to stay safe online", icon: "🛡️", i18nKey: "starter.prompt_83" },
    { text: "How do I choose the right laptop for college?", icon: "🎓", i18nKey: "starter.prompt_84" },
    { text: "What are the benefits of drinking green tea?", icon: "🍵", i18nKey: "starter.prompt_85" },
    { text: "Write a job description for a social media manager", icon: "📱", i18nKey: "starter.prompt_86" },
    { text: "Explain how an airplane stays in the air", icon: "✈️", i18nKey: "starter.prompt_87" },
    { text: "Give me a list of fun hobbies to try this year", icon: "🎨", i18nKey: "starter.prompt_88" },
    { text: "Write an invitation for a housewarming party", icon: "🏠", i18nKey: "starter.prompt_89" },
    { text: "How to build a basic personal budget in Excel?", icon: "📉", i18nKey: "starter.prompt_90" },
    { text: "What are the best ways to learn a new skill fast?", icon: "⚡", i18nKey: "starter.prompt_91" },
    { text: "Write a script for a travel vlog about Rome", icon: "🇮🇹", i18nKey: "starter.prompt_92" },
    { text: "Explain the basics of cryptocurrency mining", icon: "⛏️", i18nKey: "starter.prompt_93" },
    { text: "Give me 5 recipes using only 5 ingredients", icon: "🍳", i18nKey: "starter.prompt_94" },
    { text: "Write a motivational quote for someone struggling", icon: "🌟", i18nKey: "starter.prompt_95" },
    { text: "How do I improve my typing speed?", icon: "⌨️", i18nKey: "starter.prompt_96" },
    { text: "What are the advantages of urban gardening?", icon: "🏙️", i18nKey: "starter.prompt_97" },
    { text: "Write a paragraph about the history of jazz", icon: "🎷", i18nKey: "starter.prompt_98" },
    { text: "Explain the difference between AI and ML", icon: "🤖", i18nKey: "starter.prompt_99" },
    { text: "Give me tips for taking better photos on a phone", icon: "🤳", i18nKey: "starter.prompt_100" },
    { text: "How do I choose the right laptop for college?", icon: "🎓", i18nKey: "starter.prompt_101" }
];

export const WELCOME_MESSAGES = [
    { text: "Where should we start?", i18nKey: "starter.welcome_0" },
    { text: "How can I help you today?", i18nKey: "starter.welcome_1" },
    { text: "What's on your mind?", i18nKey: "starter.welcome_2" },
    { text: "Let's build something great.", i18nKey: "starter.welcome_3" },
    { text: "Ready to explore?", i18nKey: "starter.welcome_4" },
    { text: "What are we working on?", i18nKey: "starter.welcome_5" },
    { text: "Ask me anything.", i18nKey: "starter.welcome_6" },
    { text: "Let's get started.", i18nKey: "starter.welcome_7" },
    { text: "How can I assist you?", i18nKey: "starter.welcome_8" },
    { text: "Need a hand with something?", i18nKey: "starter.welcome_9" }
];
